name: CI
# Note: not final version, needs further work
on:
  push:
    branches: [main]
# https://github.com/pengx17/knowledge-garden/blob/main/.github/workflows/main.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps: # https://github.com/marketplace/actions/logseq-publish
      - uses: actions/checkout@v2
      - name: Logseq Publish 🚩
        uses: pengx17/logseq-publish@main
      - name: add a nojekyll file
        run: touch $GITHUB_WORKSPACE/www/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages 
          folder: www 
          clean: true
          single-commit: true


